package main

import (
 "os"
 "strings"
 "testing"
)

func TestReleaseWorkflowRequiresCuratedRussianNotes(t *testing.T) {
 data, err := os.ReadFile("../.github/workflows/release.yml")
 if err != nil { t.Fatal(err) }
 workflow := string(data)
 for _, required := range []string{
  "NOTES_FILE=\"docs/releases/${VERSION}.md\"",
  "if [ ! -s \"$NOTES_FILE\" ]; then",
  "grep -Fq '## Что изменилось'",
  "--notes-file \"$NOTES_FILE\"",
 } {
  if !strings.Contains(workflow, required) { t.Fatalf("release workflow missing %q", required) }
 }
 if strings.Contains(workflow, "--generate-notes") { t.Fatal("old autogenerated English release notes still enabled") }
 if strings.Contains(workflow, "      - .github/workflows/release.yml") { t.Fatal("editing release workflow must not rerun a previously published tag") }
 notes, err := os.ReadFile("../docs/releases/v0.7.4.md")
 if err != nil { t.Fatal(err) }
 for _, required := range []string{"## Что изменилось", "Исправлено:", "Проверено:", "Не изменилось:", "Подписка", "Журнала"} {
  if !strings.Contains(string(notes), required) { t.Fatalf("Russian release notes missing %q", required) }
 }
}
